### ISSUE TITLE
Problem with Segger and debug/run

### ISSUE THREAD

**Issue by carlosjs** [NordicPlayground/nRF52-ble-long-range-demo#3]
Sorry, this is a newbie question. I need to perform some BLE5 long range test to check if this technology is suitable for our needs, so I've aquired two NRF52840 DK boards.
Segger and SDK are installed and (seems to) work correctly, checked with some demo and examples. 
But when debug/run this demo I get these messages. Any hint, please ?
Thanks !!

**Building ‘central_long_range_demo_pca10056_s140’ from solution ‘central_long_range_demo_pca10056_s140’ in configuration ‘Debug’
1> Compiling ‘nrf_log_backend_serial.c’
2> Compiling ‘nrf_log_backend_rtt.c’
3> Compiling ‘nrf_log_backend_uart.c’
4> Compiling ‘nrf_log_default_backends.c’
1> cc1: fatal error: C:\Nordic\components\libraries\experimental_log\src\nrf_log_backend_serial.c: No such file or directory
1> compilation terminated.
2> cc1: fatal error: C:\Nordic\components\libraries\experimental_log\src\nrf_log_backend_rtt.c: No such file or directory
2> compilation terminated.
3> cc1: fatal error: C:\Nordic\components\libraries\experimental_log\src\nrf_log_backend_uart.c: No such file or directory
3> compilation terminated.
4> cc1: fatal error: C:\Nordic\components\libraries\experimental_log\src\nrf_log_default_backends.c: No such file or directory
4> compilation terminated.
Build failed**

**Comment by Andi55** [comment]
Hi! Just wanted to add that I have the same problem.

**Comment by carlosjs** [comment]
Hi Andi
I finally managed to get it running. Please check this thread in the nordic forum. 

https://devzone.nordicsemi.com/f/nordic-q-a/46524/nrf52840-dk-long-range-test-problem-when-building

If any problem, contact me and I'll detail all changes that made it work.
